function out = acc01_run_metrics_optimized(world, contract)
%ACC01_RUN_METRICS_OPTIMIZED ACC01 metrics with the approved exact batching.
% Public inputs and output fields match acc01_run_metrics.  The reference
% runner remains available for the required two-world equivalence audit.

rows = struct("subject", {}, "run", {}, "session_id", {}, "pair_id", {}, ...
    "power", {}, "phase", {}, "n_power_events", {}, "n_phase_events", {}, ...
    "domain_fraction", {}, "surrogate_count", {}, ...
    "refit_surrogate_count", {}, "mphase_surrogate_reducer", {}, ...
    "corr_series_diagnostic_count", {}, "robustfit_iteration_limit_count", {}, ...
    "robustfit_fit_count", {});
powerSeconds = 0;
crossfitSeconds = 0;
surrogatePpcSeconds = 0;
domainSeconds = 0;
robustfitIterationLimitCount = 0;
robustfitFitCount = 0;

for i = 1:numel(world.pairs)
    [pe, he] = acc01_build_support_and_events( ...
        world.pairs(i), world.covariates, contract);
    q = tic;
    pw = acc01_compute_power_metric(world.pairs(i), pe, contract);
    powerSeconds = powerSeconds + toc(q);
    ph = acc01_compute_phase_metric_optimized( ...
        world.pairs(i), he, contract, world.stream);
    robustfitIterationLimitCount = robustfitIterationLimitCount + ...
        pw.robustfit_iteration_limit_count;
    robustfitFitCount = robustfitFitCount + pw.robustfit_fit_count;
    crossfitSeconds = crossfitSeconds + ph.timing.crossfit_s;
    surrogatePpcSeconds = surrogatePpcSeconds + ph.timing.surrogate_ppc_s;
    domainSeconds = domainSeconds + ph.timing.domain_s;
    rows(end + 1) = struct("subject", world.pairs(i).subject, ...
        "run", world.pairs(i).run, "session_id", world.pairs(i).session_id, ...
        "pair_id", world.pairs(i).pair_id, "power", pw.slope, ...
        "phase", ph.difference, "n_power_events", height(pe), ...
        "n_phase_events", height(he), ...
        "domain_fraction", ph.surrogate.domain_fraction, ...
        "surrogate_count", ph.surrogate.sample_count, ...
        "refit_surrogate_count", ph.refit_surrogate_count, ...
        "mphase_surrogate_reducer", ph.diagnostics.reducer, ...
        "corr_series_diagnostic_count", ph.diagnostics.corr_series_cheap.count, ...
        "robustfit_iteration_limit_count", pw.robustfit_iteration_limit_count, ...
        "robustfit_fit_count", pw.robustfit_fit_count); %#ok<AGROW>
end

a = acc01_aggregate_subject_metrics(rows);
signflip = struct();
for run = ["R1" "R2"]
    keep = a.runs == run & all(isfinite(a.matrix), 2);
    signflip.(run) = acc01_exact_signflip_family(a.matrix(keep, :));
    signflip.(run).subjects = a.subjects(keep);
end
r1 = a.table(a.table.run == "R1", :);
r2 = a.table(a.table.run == "R2", :);
[common, ia, ib] = intersect(r1.subject, r2.subject, "stable");
r2MinusR1 = table(common, r2.Mpower(ib) - r1.Mpower(ia), ...
    r2.Mphase(ib) - r1.Mphase(ia), ...
    'VariableNames', ["subject" "Mpower_R2_minus_R1" "Mphase_R2_minus_R1"]);
out = struct("subject_metrics", a, "signflip", signflip, ...
    "r2_minus_r1", r2MinusR1, "pair_rows", rows, ...
    "timing", struct("power_s", powerSeconds, ...
        "crossfit_s", crossfitSeconds, ...
        "surrogate_ppc_s", surrogatePpcSeconds, ...
        "domain_s", domainSeconds), ...
    "diagnostics", struct("robustfit_iteration_limit_count", ...
        robustfitIterationLimitCount, "robustfit_fit_count", robustfitFitCount, ...
        "robustfit_iteration_limit_warning_id", ...
        "stats:statrobustfit:IterationLimit"));
end
