function out = acc00_p0_4_shape_for_run(subjects, values)
%ACC00_P0_4_SHAPE_FOR_RUN Persisted Mphase vector and exact-orbit summary.
subjects=string(subjects(:));values=double(values(:));[subjects,ix]=sort(subjects);values=values(ix);
if isempty(values)
    out=struct("subjects_lexicographic",subjects,"subject_mphase_vector",values,"subject_mean",NaN,"subject_sample_sd",NaN,"subject_MAD_about_median",NaN,"subject_skewness_bias_corrected",NaN,"subject_excess_kurtosis_bias_corrected",NaN,"subject_max_abs_over_rms",NaN,"orbit_n",0,"orbit_mean",NaN,"orbit_sample_sd",NaN,"orbit_q0_5",NaN,"orbit_q2_5",NaN,"orbit_q25",NaN,"orbit_q50",NaN,"orbit_q75",NaN,"orbit_q97_5",NaN,"orbit_q99_5",NaN,"orbit_skewness_bias_corrected",NaN,"orbit_excess_kurtosis_bias_corrected",NaN,"observed",NaN,"studentization_sd",NaN,"observed_standardized_score",NaN,"p_two_sided",NaN,"p_maxstat",NaN);return
end
sf=acc01_exact_signflip_family([zeros(numel(values),1),values]);orbit=sf.statistics(:,2);
out=struct("subjects_lexicographic",subjects,"subject_mphase_vector",values,"subject_mean",mean(values),"subject_sample_sd",std(values,0),"subject_MAD_about_median",median(abs(values-median(values))),"subject_skewness_bias_corrected",skewness(values,0),"subject_excess_kurtosis_bias_corrected",kurtosis(values,0)-3,"subject_max_abs_over_rms",max(abs(values))/rms(values),"orbit_n",numel(orbit),"orbit_mean",mean(orbit),"orbit_sample_sd",std(orbit,0),"orbit_q0_5",prctile(orbit,.5,"Method","inclusive"),"orbit_q2_5",prctile(orbit,2.5,"Method","inclusive"),"orbit_q25",prctile(orbit,25,"Method","inclusive"),"orbit_q50",prctile(orbit,50,"Method","inclusive"),"orbit_q75",prctile(orbit,75,"Method","inclusive"),"orbit_q97_5",prctile(orbit,97.5,"Method","inclusive"),"orbit_q99_5",prctile(orbit,99.5,"Method","inclusive"),"orbit_skewness_bias_corrected",skewness(orbit,0),"orbit_excess_kurtosis_bias_corrected",kurtosis(orbit,0)-3,"observed",sf.observed(2),"studentization_sd",sf.studentization_sd(2),"observed_standardized_score",sf.studentized_observed(2),"p_two_sided",sf.p_two_sided(2),"p_maxstat",sf.p_maxstat);
end
