function manifest=generate_acc00_p0_6_schedules(root)
arguments,root(1,1) string=pwd,end
root=string(char(java.io.File(char(root)).getCanonicalPath())); p=fullfile(root,"scripts","ieeg","paper"); c=jsondecode(fileread(fullfile(p,"acc00_sim_p0_6_perturbation_contract.json")));
src=readtable(string(c.density_levels.x1p0x.schedule_tsv),"FileType","text","Delimiter","\t","TextType","string","VariableNamingRule","preserve"); out=fullfile(root,"processed","subject","group","ieeg_p0_6_perturbation","schedules");if ~isfolder(out),mkdir(out),end
zsd=double(c.schedule_transform.frozen_constants.z_e_sample_sd_ddof1_complete_rows);e0=double(c.schedule_transform.frozen_constants.eps_peak_scramble_0p05); names=["schedule_0p5x.tsv" "schedule_1p5x.tsv" "schedule_census_intervalperm_1.tsv" "schedule_census_intervalperm_2.tsv" "schedule_census_eps_0.025xSD.tsv" "schedule_census_eps_0.10xSD.tsv"]; tabs=cell(6,1);tabs{1}=make05(src,double(c.density_levels.x0p5x.generation_seed));tabs{2}=make15(src,double(c.density_levels.x1p5x.generation_seed),e0,false);tabs{3}=make15(src,600101,e0,true);tabs{4}=make15(src,600102,e0,true);tabs{5}=make15(src,double(c.density_levels.x1p5x.generation_seed),.025*zsd,false);tabs{6}=make15(src,double(c.density_levels.x1p5x.generation_seed),.10*zsd,false);
for i=1:6,writeT(fullfile(out,names(i)),tabs{i});end
sha=strings(6,1);nr=zeros(6,1);for i=1:6,sha(i)=sha256File(fullfile(out,names(i)));nr(i)=height(tabs{i});end
manifest=table(names',nr,sha,'VariableNames',["filename" "rows" "sha256"]);writeT(fullfile(out,"schedule_manifest.tsv"),manifest);
end
function t=make05(s,seed),rs=RandStream("Threefry","Seed",seed);k=false(height(s),1);k(1)=true;for i=2:2:1900,k(i+(rand(rs)>=.5))=true;end;t=s(k,:);end
function t=make15(s,seed,eps,perm),rs=RandStream("Threefry","Seed",seed);sel=zeros(1,951);if perm,q=randperm(rs,1899);sel=q(1:951);else,b=[1 190;191 380;381 570;571 760;761 950;951 1140;1141 1330;1331 1520;1521 1710;1711 1899];a=[96 95 95 95 95 95 95 95 95 95];n=0;for j=1:10,q=b(j,1):b(j,2);q=q(randperm(rs,numel(q)));sel(n+1:n+a(j))=q(1:a(j));n=n+a(j);end;end;sel=sort(sel);mk=false(1899,1);mk(sel)=true;rows=cell(2852,1);n=0;neg=0;for i=1:1901,n=n+1;rows{n}=s(i,:);if i<=1899&&mk(i),neg=neg+1;n=n+1;rows{n}=mid(s(i,:),s(i+1,:),-neg,eps);end,end;t=vertcat(rows{1:n});end
function r=mid(a,b,idx,e),r=a;v=string(a.Properties.VariableNames);for f=v,x=f; if x=="label_index",r.(x)=idx;elseif x=="label_time_s",r.(x)=(double(a.(x))+double(b.(x)))/2;elseif x=="z_e",r.(x)=max(double(a.(x)),double(b.(x)))+e;elseif x=="source_complete",r.(x)=1;elseif x=="movie_time_linear",r.(x)=double(r.label_time_s)-240.875;elseif x=="movie_time_quadratic",q=double(r.label_time_s);r.(x)=q.^2-481.75*q+58020.765625;else,r.(x)=(double(a.(x))+double(b.(x)))/2;end,end,end
function writeT(p,t),fid=fopen(p,"w");cl=onCleanup(@()fclose(fid));fprintf(fid,"%s\n",strjoin(string(t.Properties.VariableNames),char(9)));for i=1:height(t),z=strings(1,width(t));for j=1:width(t),q=t{i,j};if isstring(q)||ischar(q),z(j)=string(q);else,z(j)=compose("%.17g",double(q));end,end;fprintf(fid,"%s\n",strjoin(z,char(9)));end,end
function h=sha256File(p),fid=fopen(p,"rb");cl=onCleanup(@()fclose(fid));m=java.security.MessageDigest.getInstance("SHA-256");while true,b=fread(fid,1e6,"*uint8");if isempty(b),break,end;m.update(typecast(b,"int8"));end;h=upper(string(reshape(dec2hex(typecast(m.digest(),"uint8"),2)',1,[])));end
